site_name: fiware-iot-discovery-ngsi9
repo_url: https://github.com/UniSurreyIoT/fiware-iot-discovery-ngsi9
site_description: FIWARE IoT Discovery Documentation
docs_dir: 'doc'
markdown_extensions: [toc,fenced_code]
theme: readthedocs
use_directory_urls: false
pages:
#- 'Home': 'index.md'
- "Installation & Administration": manuals/admin/IAG.md
  - 'User & programmer guide': manuals/user/UPG.md