#site_name: fiware-iot-discovery
site_name: FIWARE IoT Discovery
site_url: https://fiware-iot-discovery-ngsi9.readthedocs.org
repo_url: https://github.com/UniSurreyIoT/fiware-iot-discovery-ngsi9
#site_description: FIWARE IoT Discovery Documentation
site_description: Installation and Administration Guide
#site_description: User and Programmers Guide
docs_dir: doc/manuals
markdown_extensions: [toc,fenced_code]
theme: readthedocs
use_directory_urls: false
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
- Home: 'index.md'
- Installation guide: 'install/install.md'
- Administration guide: 'admin/admin.md'
#- User guide: 'user/user.md'
#- Programmers guide: 'programmer/programmer.md'
