site_name: fiware-iot-discovery-ngsi9
site_url: https://fiware-iot-discovery-ngsi9.readthedocs.org
repo_url: https://github.com/UniSurreyIoT/fiware-iot-discovery-ngsi9
site_description: FIWARE IoT Discovery Documentation
docs_dir: doc/manuals
markdown_extensions: [toc,fenced_code]
theme: readthedocs
use_directory_urls: false
pages:
- Home: 'index.md'
- Installation guide: 'install/guide.md'
- Administration guide: 'admin/guide.md'
- User guide: 'user/guide.md'
- Programmers guide: 'programmer/UPG.md'
